AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - db/seeds.rb
    - config/**/*

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# Line is too long.
Metrics/LineLength:
  Max: 128

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8
